# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#

hub:
  services: # added for dask config 
    dask-gateway:
      # apiToken: "<API TOKEN>"  # ELENA: needs to be added!
      display: false
  db:
    type: postgres
    upgrade: true
  config:
  # Could be enabled later to persist login info and redirect directly to OAuth SignIn
  #   Authenticator:
  #     auto_login: true
  #     enable_auth_state: true
    GenericOAuthenticator:
      oauth_callback_url: https://nb-vre.cern.ch/hub/oauth_callback
      authorize_url: https://iam-escape.cloud.cnaf.infn.it/authorize
      token_url: https://iam-escape.cloud.cnaf.infn.it/token
      userdata_url: https://iam-escape.cloud.cnaf.infn.it/userinfo
      scope:
        - openid
        - profile
        - email
      username_key: preferred_username
    JupyterHub:
      authenticator_class: generic-oauth

proxy:
  service:
    type: LoadBalancer
    loadBalancerIP: 137.138.226.36 # may change if LB needs to be created manually due to bug: openstack loadbalancer create --name <lb-name> --vip-network-id <network-id>
    annotations:
      loadbalancer.openstack.org/network-id: "798d00f3-2af9-48a0-a7c3-a26d909a2d64"
      service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
      loadbalancer.openstack.org/cascade-delete: "false"
  https:
    enabled: true
    hosts:
      - nb-vre.cern.ch
    type: secret
    secret:
      name: cern-sectigo-tls-certificate # using our own certificate

    # Option with letsenrypt (not working, cert gets not issued, the problem could be with LBaaS timing)  
    # hosts:
    #   - vre-hub.cern.ch
    # letsencrypt:
    #   contactEmail: eosc.future@cern.ch

singleuser:
  storage:
    type: none

# ingress:
#   enabled: true # can be an alternative for LBaaS in combination with proxy.service.type: ClusterIP
#   ingressClassName: nginx
