apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webui-vre
  namespace: rucio-vre
spec:
  interval: 5m
  releaseName: webui-vre
  chart:
    spec:
      chart: rucio-ui
      version: "1.30.0"
      sourceRef:
        kind: HelmRepository
        name: rucio-charts
        namespace: rucio-vre
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: webui-vre-rucio-db
      valuesKey: values.yaml
  values:

    replicaCount: 1
    exposeErrorLogs: True

    service:
      type: NodePort
      useSSL: true
      port: 443
      targetPort: https
      portName: https

    image:
      repository: rucio/rucio-ui
      tag: release-1.30.0
      pullPolicy: Always

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

    minReadySeconds: 5

    # proxy:
    #   rucioProxy: "vre-rucio.cern.ch"
    #   rucioProxyScheme: "https"
    #   rucioAuthProxy: "vre-rucio-auth.cern.ch"
    #   rucioAuthProxyScheme: "https"

    proxy:
      rucioProxy: "vre-rucio.cern.ch"
      rucioProxyScheme: "http"
      rucioAuthProxy: "vre-rucio-auth.cern.ch"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      path: /
      hosts: 
        - vre-rucio-ui.cern.ch

    additionalSecrets:
      idpsecrets:
        secretName: idpsecrets
        mountPath: /opt/rucio/etc/idpsecrets.json
        subPath: idpsecrets.json

    ## values used to configure apache
    httpd_config:
      legacy_dn: "False"
      
    config:
      policy:
        permission: "generic"
        schema: "generic"
        lfn2pfn_algorithm_default: "identity"

      oidc:
        idpsecrets: "/opt/rucio/etc/idpsecrets.json"
        admin_issuer: "escape"

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

