apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease 
metadata:
  name: cern-monit
  namespace: monit
spec:
  releaseName: cern-vre-monit
  interval: 5m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: cern-monit
        namespace: monit
      chart: cern-it-monitoring-kubernetes
      interval: 5m
      version: 1.0.0