# apply following with:

# RELEASE=dask-gateway
# NAMESPACE=jhub

# helm upgrade  \
#     --install \
#     --repo=https://helm.dask.org \
#     --version 2023.1.1 \
#     --namespace $NAMESPACE \
#     --values config_dask-gateway.yaml \
#     $RELEASE \
#     dask-gateway

gateway:
  # Path prefix to serve dask-gateway api requests under
  # This prefix will be added to all routes the gateway manages
  # in the traefik proxy.
  prefix: "/services/dask-gateway"

  # Number of instances of the gateway-server to run
  replicas: 1

  auth:
    # The auth type to use. One of {simple, kerberos, jupyterhub, custom}.
    type: jupyterhub

    jupyterhub:
      apiToken: 886a08835985f73c7a600588f7d0991af76c70992f479b3b6650cbc2d3dd9575

  extraConfig:
    # Note that the key name here doesn't matter. Values in the
    # `extraConfig` map are concatenated, sorted by key name.
    clusteroptions: |
        from dask_gateway_seCorver.options import Options, Integer, Float, String
        def option_handler(options):
            return {
                "worker_cores": options.worker_cores,
                "worker_memory": "%fG" % options.worker_memory,
                "image": options.image,
            }
        c.Backend.cluster_options = Options(
            Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
            Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
            String("image", default="ghcr.io/dask/dask-gateway:2022.4.0", label="Image"),
            handler=option_handler,
        )
rbac:
  # Whether to enable RBAC.
  enabled: true