apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reana-share
  namespace: reana
spec:
  encryptedData:
    share_access_id: AgBJ50gNA9rdyt5RSQYJLWg9z+jPYpbdfqKDPS++76Me8T0SfHimLdI++G7zg2wzUDOOftoAfrCVE8t/VJSzyYGVDd20Yjl4bU7+/ff/qX/9hsc2so3Oi+Iam/ynTAHhjz4gsuc7N/xSO8JwiAy4MMkIU4tRWANP9NC0xX79GYJttkOUPoflNaOFMy2PdCMlTIVeFGbrLzArWKliJAH9dLHg/ezkxxa5kQ96MQrdmECnfmogf7yxJFCpOIvNeWHI/rIJxrDEkS5g3Ofwt/U6rX9tLxfQdsgoBxtsb9gRojBxLhJJ0TepPk0k5I3OUl4i3QASPmk5tuSGoBNSJx+EagRAIDwfy3ZaXYNqltj6RRW9qj2qHJMnIaUHZ0SICPTbPp/WiMSEwhQtV1o5np7qky7dD7Q4f1DM7nAs2E5F2dGtHx9c+xsU+d4pkGL20vyFSt3tkojEr5kDpK+oFqqNNmHcBdtF5SH6e/k4PvCNO7KoObLnnI8OlIaNHEIhjtY0p4vio9vABd1HZi8OE4SZ3m7+8Iyu+PUse4efSHZwXnjigFfjrDiry5fp9GF9ST1FoPyxVUPViEVfwIyKZcJLW2LEVY3uB4i1Moustcfl8rUgLStmDB/l4cmWBLGotrj/W6QeHuied9+GR0Y7LdB6/YL3Cjr+FHPqUyKKqra71bOhKVETmdCyt4BQLse2kaqjjZoOTq4pQ3qgRApD4iZONpn+lBt+ccreFvZieRy7r2N7TqMBmp0=
    share_id: AgBWkLlKa9tQMuVZHGqpQxVjVRHdaONhz30H9OafXsQemvDB3MA7SvCJuksHAC4gXNsDZX76aPDys8tuCJNrUwaRwebNDDxizScYcHPo92vafIcs/aOxziC7KGDZGNiRnPRWJrHVhLTt9yOdkh0SdXmR+B6inn2UQivu8JXQK8JMGY3CkmwG6vNLCCw+Ji3ACLC4PiEskEV4uDuw7UPDD+HcGg1TXyoCuEvGKFeMhWXif9QCfDwQ1i/oJxlCNZyU+N7aVqhm0UgRkcc8UDXh7fJHbhWqhfQhaCglOmJW7I5xnB+nDPUp7W9oah79WRaMocrFeMNvGmmU8FoNkEvumKKbN0oNeBcRce0VuRJmmIKFIdneS8jq6eb1AgiF1Ob26MiB/1ke0xP7VrT2UJaehFggmzPLZNIhq+gbJZixFWeUe8ei46zchmQr3qwu7+PHt8+6quXTICJ6Z4nwZWXoOg8nblrEh0U5FG4bsa6eVOyIn6xKvTpoIt282q5n2b+lkolcTFMLMTmoGpX/7aOjIBQ1ouUauBKz3FMOqBcffJ5ODEUu4jJGZsWCDjl1eqzxa+Tchuh6aZ1a5S5m3dR6CK/MzpRZgnG+iE/dA/h45wt5ohpBej8GZfAGIYpmovmDPACLXHgfld/+zFfq+Xs8AYek8BzX5XEwyEp6Ceu2huwhgTVQc7cGAh2QWmtn6bAYbWXD8bs3KTqhymYbkckvLyY+bbVDKknoL5K4WkpOJlo5+Bv+z0k=
  template:
    metadata:
      creationTimestamp: null
      name: reana-share
      namespace: reana
    type: Opaque

