apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reana-db-secrets
  namespace: reana
spec:
  encryptedData:
    password: AgBwnbqTtHFEUJOsWjVO+0KFOeyUYK7yTPR0nye5J3fF3Ic9NOpogERKfjECzxoWlJiG+aazKW5VCAwvM5GlQrf0exjMluouTHN29HCkqp1ydmlnmfe8TUsDTJKZFq3y8cm/iXUYTywZYb58RUm98mNF7x40N1WtHx0r8NRV9urmNbVCrqOEGnGdy9xaxdzQMQg2mNDMcJl9sS19kjVZK5rLSsNvGjRgyvsULr3pNrAMUpHU/PLsilM3qQERpLGFXVGuG2lgn4Nc7oui915zxOstzqmfgf/E7+8KNNBpGNGf1GiQC6sEu1tT1u7oajYp89tQtxDge8YMKW6sAZopWwMdRbSVBffgNgzc0rdo64NMkwAGXhYZ1EramqcME1jniZELBxA1C0j4TZM4IsfISkcOb38deL63dnQMezrJ9T8i0Ac590kNmaNetB7wDxJkdc/Oa8Du+hhdIWUtteGvYhYx2KjynB828iPopkzR0e38RyuXtJ+jcpU7EGOu6PQrgNRH21TURV6pAKVYAUPCoil61Oas/SE3uziGE9MeyTg/XbvA6BTr0pub21Znb0kNWzff7qPwtZkRT/SY56oDSbMB69XhL3D0J8PrlKU+2SWBbsXvIfltDTsdHxhpJjkfEFmQ/6sNEbXQbXdy6lFZcWZFDM4Pf37XxAlVwibqws7NwnalhwQ+dvCn42M0uERVGcHUwM8HL/n7gCsBitB529xaWdicqQ==
    user: AgCtfyToVhA7IIqmn3MbRVgvH39DeKS+8DcPhg7kMxrIckWZZ+vJUg33cnP1/m57UjiD/VTNQfuZWhW5fjyyPg9zUn110LiUvLBttBMVrpzIfZzZpfCmcYRTVlfAhY5rvmK3BMa8dHXyM4+wj86rpHzmQIAsXzZ0NSwNlEXRshpgFqAalsTKwhlTfk77RM5dIZwZSnyQxzNsHKRFU2am0aoZ7Xtw7XovRVfY2HaF+JIcUMO1Ugfj5oVpcUmAoCpGbaE/dHmQJQVZgk6JX9ahkdmUn4C3D8jBCFuE+loEhDbUHrEdb7hmi65eur+EOB/smp/IfQMKicfCI/Z3huXYveLKldT2vrr2VAxZeCWo6qZVUiCfPo5qlIl2hweKUdjPByZsYDhcn8mMWDy8qey+Bxj2XhPcBELvyR58VUIonoLDnAkaLg0VbRYgUtVajfj2HqrmHsQ70fXjkcH0wGrDDsvjwzornPWlwld8xqbWr+IGlTDo4xXyt2vZivUOC3z5Jbi0/S2TQbhFfMqtOXl502RbuEjyY6N5Vdfs5k4YzkhIZnktssbg/vPzhiTfLzKfcvx7MUWRRR0l715cF8tM4dfYfoAYofbUDeAvmcOuir+/dVwz5sDQNOoz/m8PDthkRKm43+H8oe4gLsikdAvt6McIyKI0FVT3GB7mk7nQHjQifREKlf/q8MH5jgT9Cg76U9mg+vGtcQ==
  template:
    metadata:
      creationTimestamp: null
      name: reana-db-secrets
      namespace: reana
    type: Opaque

