apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reana-vre-iam-client
  namespace: reana
spec:
  encryptedData:
    client_id: AgBaa6OrouO7NlbSWsa+KXVjIUl9Ux/ZgjAkWdpq2O3L8HkECgsm3yOEfYxOvbRC0mdwyVPhiu8ksSmCTEQDqy2hL0PwK6pJ2X3uthB2F8j28D/BS/UTWnh5p/XO/6a+Pz86XgzrT+wGQw196PcRBtykuc336MnYbLySiZj21nzIBjMduNEXF85ScH0vWDjyFPcJIJURbJvzRfly/CwkTew9ntiJ4fKg52ciR9ZVJvi3Kr6k9C1zQoy9qHXIUtIGQbpwQgJ2ZwpPDnrk9v8GHk90jJD3khofLCXO0ITY2e0X965hOoiwlMFLmFFvG++4oEKOPCY2/E9ooyJwnBtlzrH38astrBrc/Ya5pVpSGUqJrUGd8jdRABoF5AR26wX8vsUU/4Tbysm1V4/qlWN/ad647//nW3h6mMh3hEX9E+h6ut8I99esvCRaBU4AkE61Rqy5u0oNQ9Ly+I+Sl8Rh8d1AvcQQbImar9T7Hn4gnPNAShKu5X2McelKjtmVtD3lX83bzcT650ieI5N50BkycqeLT1g+5dUZxac/HWyDN9JzcVUaa18ZSH4xK3GhDUXJFOsI4vlb/M0581i1zNtP1ALZ3VtZmgGvOgYS0/eCluSTaZ9DJ1LXDKQlbApEstsUe0/JxyNFwNYZP2fC8PSC417Rb6uze4G2L5J8PXj+tsYTqcv10WK4HUXagadASdq8IZy7owXgICLel0kW05jCqx8lfWC7Kuu+/Xhbz4aOlo0cB2PavW0=
    client_secret: AgBdIm3s7ObdkEdfV4yWBsizibBmoWupysX1ZZNr5IG26G1Ex645EP/dBniOevvI7Iu+zqcivWRHg6swTeZuT9Fr5aXVRD0d+Td3c01GCpWa/9mMZL3s5hhutVUGHIbNj0OaGudRVNrNyPAg2CLcYERM5EapBm0KH67l9PVyAT7AqmQszsQujOVmAn9v+I1BBbw4aUpFegYfzaKT8NMnaaVMMY3pkQwQzStYXcIYevT3sl9tZtzHvrngCaKdE5flJZJlaci3gWIS/dEY14CNweKRo/jxHkKfSSf1E0+I+nGwcJFDKF8SIiWR0IMWrx3O3NCoceqVwVA59OKVbCtP9C0L5bvYXfI5HnJCDsmfmrnDKhlMmf5RWl2dRs2cSx8eVJJxEzUV+/q8BUOcR8WIUVOnVZaJo9Zrf5OSG7l3dPPvTcD1pOKuWu/vO5XfDFgHHk4kyMpKm8uYkICTcZ+TPBUP2CXwVEA0uMOajxoMea3E+HuCA0dufYnItPj5zXlU2yfKS9ssc959EHGNKupNbnsbC5oisl7x1mhXIJj9R0HFFIIAp9LBjd1G+FFsX/0DS5pkDwgLzjwYD7Es/fostcJU0kt2Jw5a2FDCctvgBpgs+ks4HtFP6e8A5j96SgX1XT9xfuZZ3CMIYXmTm2zdrMb88aiT07awk5Hb59f6ygBOsMVsF0uO8w3i7m8AHRtW1zgrOk4CaH8KhRxrc8EHCQiNfnSVBnSaWHDSKqyZAu3kETKbVDE/mvgyQ0fcQ3yjOnGeVzRUHQJijZqLjQjkLFinJgVfnWw5V6otOP4rtC2EKwNouCLK74Q=
  template:
    metadata:
      creationTimestamp: null
      name: reana-vre-iam-client
      namespace: reana
    type: Opaque

