---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reana-iam-client
  namespace: reana
spec:
  encryptedData:
    client_id: AgCYOh05xvmClNrI7o9jpydJ+kP+BAReZWqpuU2J5mHRRLPEDGwfixF0sxukpAx1vZwvWAO4dGRnwRiRKYIKgMpdXJdvZ4C6p/AiuYyuj0xxWaq+WR2Dxsa3VvCvcm/vGiTG5ec+uVHsvztyyVRaEELyN3LLx1Elon8tVuUZ5hWbyH5M5N8YAa2bOD31l8IhQRrivrsn9MolEz/1UGEJw4dVpLFkXssqUZMaG4Ab+n1W/lMlro451TgALjfe5nwJsJNo2ffdkwCG+5oDav8BqIFm67h6hOwlI92rYwxKimyUukTow62FPYeSarcJLvaa05Dfauqj9OYA2RpgMvzhIoCaQHi8HB9yey6DrR9kwEZ8UFcTTFC5rx9YCRDYsFegSiirTQQbrZc5wiZ7pOCxyskAPejNXPVtwPAYvsUksYlSGpff4vf/2zJ8ccHwQNw3wuDB77Fznz4zKewM+sTZ2PeB2l4iiOG19Tze2YyMkJSo3YnNQ89fk8YmV7XDeJKon8KwZi2mDQTMm+6utRFbTg4bIMwLc5H1Agl7/MShwz4cTomjLvxgWNiWMPyggIpxJ3HMD/KONl/auBctLQwHaUc512mqSO4qlZ9J2lx7IKCAKjzvdbejGgkU/PMelYPTUjU0f3qgFt4thf6Q6rIehKU+Tj8SHH0Q5z5MSAmvmVFokAjTcsBcWbH3EStfXQEZl+px9MAcvJ5MBwp8Q98W06zz53fC1Z3n+JBM83bB9DCP6RzYCuo=
    client_secret: AgCOPGcLBMaTrfaq9mpncrUipFC13gsJnDm+FEWY7c6oPKfH7H+Y/EkGYy95S38kNYfDjrWvDiQtsF94XmJvV44JtG1gPfeaNp6tYpFgjhIMlbpzUv2MkDdgK9dvAkDGN2BxiPjAGdXsdssdy4K3j3kC49mKyCWAh7QG4MLvqUqJu4zUnLQSAYgDAp6t1xeCdwKtdSwtCPzlmsIJ2R8yRrmNMrchAuBFxL8nwy3KuB5nwvQHk5SZzD0MEjFjf2J+RuJNMwFsp7aVd2KIeqpdLXY0ab6uABW260yvaU/Wq4wKh96dZe1sTmlRHP/t1/ph5gOTMamudmD5/ak8rIo+r8lMK6A6CJflT6G8m+hh7uDRKtRiWHThcMh6Kox35b3fYYxGrfa98vpRNj/blsWpFvKYVWgfKKOofbb7BeQyDVqNdS7UZzzUwoyrFaNvD5aHDh1SLQCF1jBEh5ELql/g2Q3w40wVudZA+qv8RwjtjYQtmZyuVr9jzKZ6/nd5759n4ovYGsPLvBeCutj6iAHSdkO/eAkYj9kbU3CMzywXBNUsGyf+/pIf++ZoOmpX0A8i1JMZ/Ibtq1W3DpGijaAPkytf8BUBTbwNH8ZS3DvU522gERZ9dR90QZfyK2rk6pGcXP9GNZ683IrT3EE5GR5xqZqcC4mEJGj+Zd4Dhlp1nElpBvl4tytfxpC8brYwXIJ6gBWGQaAJ8YqyxH0FOws8DpAN2LU7D04tU9bY+z1yoe6ViKA+VsgKLNPjRTI5BEWak6guQ7Zw9DmxCO0e3/smkrFJCqz5+otzNfKCDObXLH8AQ9xhFuSBDl8=
  template:
    metadata:
      creationTimestamp: null
      name: reana-iam-client
      namespace: reana
    type: Opaque
