---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reana-vre-iam-client
  namespace: reana
spec:
  encryptedData:
    client_id: AgBkec2BRIjcIL8/s3DrbhK16a1mbDmmDzAC1U6mZVBp8nT0M3NQ9FLEluNv56FSu1S35BhubYk4YvzJTeekgsuxFl5NZ0E7WkBFxLYNuXe9Za8OENZUU7q0WsobVkJdNy01Z4/jCHVyypxL2/ysYSBN2Uw2S0Sv3dhiQoI+SjdgTnU4hUscTMCF39xy1ilYudalBxJP1kargst3/J2YRmkNrfYUtKRWcpDnZivvooy7ej9NC89IYIeuWy1/rL+pGpnzt3UwxlOfYmALtr36dRBl4T8mmOMoHe1gPEkhD50ETn1hWS7E4ASvd840O+X26Q9vw/tKrmSLlnAiify/M0czXShPsdrv2NisDzSCMpR57QK4VY3E6K3wYcQqAwZBgSaHwjE9PtedeJwQuleLkMnhGBpQ9HajvNCAH0VJFRvWnr7ZVB54OXYpEKrf6JV7QtJ2oDVJHySvqpb2Yc2FbkHu0aMjy0tx5vgCZRs0aJyaguRwMWG6upxvoDpdh1uGrIstrPeuCDbgNAJ/Nf5+pAL0edQByBoeSQ9qt3xuBVcxjS4UV0oqsAbpSyCXes+LxaL1XWK4axLT181FE7BnbBM23rZXgdcQxW1G9AZiGwBviUXp73A3sKYi/xw6HPLMrPKi+qiFhVE3y3xHNLLN4UzEG1uyaL0p6lkoHX1SfvsAaef0jzACgcZYHuF9g7qFx2K8aAr0BOsWKJfeuYdoBQSehMkqpE4QZb9H51MXKwGkcGpXG00=
    client_secret: AgBN1b5bfRKYBCWEtaQ7jxQpi7WOOusSRp+KKflAEieqSIV6maeiPZCbLz0id3CXp/Ig8GKqdr55kfn+5tPV7AkfiJ9I5mPeLeLY/V1/yqsBYUc/pY63dpJNdijHPopI/hxwoO6Bd2fktYOCCiqxbEPqxtFez5VcIoq5NhOpPNuj4A1WNENZuTDeJk4vB93HTSnlvb1eECVByOiV71Co+5lvQv9s+bM6YaCz34hw87dTCTpg/6Wl4ezvYV73Vfzz22CSDoUNGIGJfURts0pQ6fHKdPeW/D+/4n45sS8t13Xf+pxDOdaBiuNOQhtNx8C1Crr9TsaKAY3nAGLvrbDEY+hnxCjsZqmj6+De0e8zn5Exe0pg5W1/Hc3c/IW+GDPcvIDkRSh5qis53ek68OiPXfaY4jYCjP8MP8LF2rD3CkE3BKeTxxcY28I315FYuHFWbr2GSXI3xQoj6E7jxHpPxsq1WQpTK4/oGQRFb4+S6TXut8Ey6cgpVJI6OfcXt9huzJTkMNjuW+qmqcEhzOlgBxA+Ohjv2WEOCAn4+pbcaWsHdWJhLtZhPOKCQukhdr8l5DXfJKoJegjQ9WHWI0R6TQZkIshloG6V4YqTXzHlDPDL5X2s1+uAVXJQPiX5LE6fxtLEG/aigQDMeL2U3DYtN9In37Mys/LgT8ZnzFcEFCJmCcETbxPYPPljqD4ZQXg7ahIMI78VGWeuHwFTzom4nZk23gDkxgx17w5UWG4LzVYqZK0K+8+ncEYWOoLuNVdqp7ABvA1KDz6Y5bLoGWPKoGUWD4EUEj/kqtH2WWVUAAmKs5siA5DIvJA=
  template:
    metadata:
      creationTimestamp: null
      name: reana-vre-iam-client
      namespace: reana
    type: Opaque
