apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvmfs-all-repos-test
  namespace: jhub
  labels:
    app: cvmfs-all-repos-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvmfs-all-repos-test
  template:
    metadata:
      labels:
        app: cvmfs-all-repos-test
    spec:
      containers:
       - name: idle
         image: busybox
         imagePullPolicy: IfNotPresent
         command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
         volumeMounts:
           - name: cvmfs
             mountPath: /cvmfs
             # CVMFS automount volumes must be mounted with HostToContainer mount propagation.
             mountPropagation: HostToContainer
      volumes:
       - name: cvmfs
         persistentVolumeClaim:
           claimName: cvmfs
