apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rucio-db
  namespace: rucio-vre
spec:
  encryptedData:
    values.yaml: AgCnZe1/w2PjbkO/n5Sc+o8I/rpUFZceLI/sRRw98lJ9ukUS9A7WX8mEzrGeEFDM8gsuir6yvNidowhk3ubreECPbThiRQsBSZXydkjPXGKQ+GgbxMqdGv3PAJJz4eipCK4UqFxMr07hKRVYNbZ+2Hhw4FFX4un0cPW/G4LPwaK8QmfTQoSuxf9KpsklU6b13Le5pNOz9gzPjHuo1q3x7IeKdar1w86lrVyHg0AHJJp5cLS2hK7QfScpjXUxug2OgvQLzqcn9R45f8TAxNhmt0EwtHDgfYbgjlkHO+x/7+OwvV0OVZlXdNN+CsxrSa4wSbA+XP6YpqXAds34iEFKMeP+3oRVor6LasuqiZLnk7YCMB6rcv7Q9WqAg//2HTJvEW7ad793oFhV23/s3NBKC+Dyjpsx49fYMie5esy+lH1g3n/372pwUyl5cTpqUR1SjYrNivh5X5V/P3UqDHh92tB0rFzGz70vAa94bCtG05M4FYHKhMeEd/9OW+yDSvWANBI2pKivnQ97o3OifaPcK90aVbiDRMphzS8wg8yTZxTDz+I5BBuRyHtCQjY4+WSXqfhwaTk9dDft/DGdEDLR8giGvZPsiJ6wFefsxsIpR7xc+EybkaLFbP2NfsSWllLdpBVF1JnaNT7m44ly+WabZsIQiGCrp37qFX5AHYqcNG47qmrK1uquRK0uz/V60CzD3T+yfSRFB16coDPSji4ojvq12fuMlGlcIBD6x/uZA/Etp2Or46HZJQZ5Kr+Lgwe4Fcm7WCCiPpJGRskefJTBk9UwmBHHdc33UjZfL11+k5tt6C1R+5484yiTSb8ZEFacP/IP8KacCVfa+nbA
  template:
    metadata:
      creationTimestamp: null
      name: rucio-db
      namespace: rucio-vre
    type: Opaque

