apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webui-vre-rucio-db
  namespace: rucio-vre
spec:
  encryptedData:
    values.yaml: AgBqFHsbgsviLYZ/0mCliSQpxyYrC1ygiw60oRR4MRGz6b3Y8xxntKYM2IGFnq++WjMc6Hau3VUzFZXTKPeRJCTko4Z+pIcfCvTcFJBtbG7H/wS/ovR8UEFPlxCD89wKS9J47sisWyxMa766+EpatTp8komHv/iip1eDXkSLd796cEzh/U+/plAbIP2XEXEDKPLkhq84CiGK0Y+/lGk1ol0VW0bJ1QjYwsQ7acUyKQ03CVac3v31DiggchDUc7PGf3FoHEFtp3rqTkPYZvMXFD9+3VzW9fCBJdU0cToQJhTl0fS9KwHpY3NfQKm2EZGVVSru4R5V8GjPP4yUo2F4BoYqFYjXqY2rq/ovHFSVRs9BpYJGnHRmfR+mqAHwcQRcuO42p3+iD/ajhJyUb9t33rnwoyh7+hWDo/zDOmv5Tq34fu0wdC0t6wP8XcpfN+1E79rRzjXPrnGRTefO9DxbtGRc7Dfqc4yBiCvm1V8b6GEsFYALAlzxEB0EKA4cC0YF3qXi/kzKLXtlNgrnDvT+rpFlId9AI2nPJZPL7ZQoweJ+kBahLeQ7gBRg/JSFipqNQSM6aZZnLHWja/U8FNSR1Cq2GUSXSbHSaaeqKbzgXtEW5M0GW/lF2VgVwcNP2agjNKLLB4mjzUluUIAvXeSsY1zggIM/f2gOKBiSv3mOifNB2/QNLBIkrrBzjsKOVC7KP6WmSUck0xqIELM8OF6xSU4+bWT3sLD1n1iBVqQlwXqw0YDBYKvqNg8PjMTEDB+NSKOeK/+s8cdh3b5cNBTGj6LRac1Uz/0/Ao84MA+ADVOnj2uLD0eBxhdIKJvA2XB7z5h1zVJPZgtKPt6b
  template:
    metadata:
      creationTimestamp: null
      name: webui-vre-rucio-db
      namespace: rucio-vre
    type: Opaque

