---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rucio-admin-iam-client
  namespace: rucio
spec:
  encryptedData:
    admin-client_id: AgAW0OAhq4CrWG2lYNn8J8hbItmsJ29ydXv+B0PMUTS7EMo+h85+GR2bJ32qKJZ1oNmDbd6FdmZdbDSlfmxNsDRXckoBPopuq9yg2N2PpMD/qQ2C9lPjyYjR+P89AkhYQVqzp9OpNT/xk4uCq3NtKdvvxIcDV6HWsaQDEwM3OSDJek0mDNzP3YBPYPGg5gd/ZAtR3hIwSv0CAk2w3PYQ7Vk9g9uN8gRVu40fwkyE7vg8L/gEZstN43AF7/L7Zgpo0SUoDSdBr+NfPcz6KcHUq5s23ICdsALRXDHryU8DWGtKlUFBuW9NM1/pV19UrO3Z5hYT2uBoCASIOiNnOpaGN+WjiIMv7blEq689OG0vFahpZVw7wTh4S1suifAtmJIdibSRVL5BuTg7k31dkmgjRvf0bOY9+psnzlM4UurcZlCgCJaSxQTVuJDnLVnV4JZdhmiIhZrAmCZiYcu5uVMtSjGfYZiCyKGwJWN7NgpC3YyArOnp0feoh3fyyDle8i3sGjl7+2labGVAbE7yA9Uo5wlElsnyb0eYj5gavFAO/LwltVy+QSzIY2KU+nNpZfLfgjLivM6D87Wmspc18xIsg+8RHr4Pcj9jqmHQZlQMhhJ6p5j/Hvnl5wakTDMxhbs+38TYlHLHc5cgEBCCFTY+hRXhDvP7YV4IJaShZH3Jh7DzdEgY147AVVcLfzgUgk4FfDdNKF8DqniRmfKY/p0pIEnmoWlWU0oDt/6ihonDVi2cvNBqBgc=
    admin-client_secret: AgCwdlvPsu/82TPLrZutViDOjrfcT0H+5fbop/Rw4kxmsYcaazV7M1WVCWRlGDHqrJaWeU8X8p5LvgwQemmSltlvvUrTKi92HAsgboqyQ0tZiXpSs8njZeYThn5HzP2L066hFp00vXp2Uf3KV6Budd8KOP0SKRCTmgCx8pqsMq5yfM2J+IZ05mcHt/ORR2XtwAGFmrzp3IUG32tFyuS/JEyRT1yO8J6rL1JXHiwfZ6YUKQLMxTpe3PNcirz7Fp0bko4Y/ujAjWZVsK0FH3G8+IVNKS062a437Kp+vl3uljH+FF3E4hr0qEP6BL9DGimyw2fpWKqX8sLNtisZT9OsuJkC0Fxir8kDMqPxvvNusWZ/uBBBHaJBZnqaZw3lltfegT43400W82FHSc3S6u+xQdMh1rhSmLaCbkJNRcx4MCx60pnIBhTVuBbQOpd8QUhaB6+rBmixDAH0QvWFZkcUWXjwIKjcII3KBOOdRdpQl1KAJ8kfd38e6wzGgJ05oUBJJpqmOqLaZSLM22Rmz1Zm8iayGIX/OlMfAosfYEB1MFolpZ7qzVnxiP61Bxk3lKfbHBnbcLv32Vq39nj8KoUK2OtXoIfsPlU0Ux4iuY95663EVJVWCZtXl8MXjwvM1I/h2fdEbiSl/LzoyyvAwlHDwUgtBlwG2twJrdeNbgTaFUrlcsMibI2Au1sCNoLRJY/FPDCHnfzkvOgY22wHEOVGH2NkW3ox0ELRvvUHISu+j3WLs9fhbbh6iEyoM+cO7E4odsATXerdPoRSt0JrK2NOm0SG6UZAInYE8C3UIhUoTWXjtQpqpNnjixI=
  template:
    metadata:
      creationTimestamp: null
      name: rucio-admin-iam-client
      namespace: rucio
    type: Opaque
