apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dask-gateway
  namespace: jhub
  annotations:
    flux.weave.works/automated: "false" 
   
spec:
  releaseName: dask
  interval: 5m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: dask-gateway-charts
        namespace: jhub
      interval: 1m
      chart: dask-gateway
      # version: 2023.1.0 # support for python 3.11
      version: 2022.4.0 # support for python 3.9

  values:

    gateway:
      extraConfig:
        clusteroptions: |
            from dask_gateway_server.options import Options, Integer, Float, String

            def option_handler(options):
                return {
                    "worker_cores": options.worker_cores,
                    "worker_memory": "%fG" % options.worker_memory,
                    "image": options.image,
                }

            c.Backend.cluster_options = Options(
                Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
                Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
                String("image", default="ghcr.io/dask/dask-gateway:2022.4.0", label="Image"),
                handler=option_handler,
            )

      # Number of instances of the gateway-server to run
      replicas: 1

      # Path prefix to serve dask-gateway api requests under
      # This prefix will be added to all routes the gateway manages
      # in the traefik proxy.
      # prefix: /
      prefix: "/services/dask-gateway"

      auth:
        # The auth type to use. One of {simple, kerberos, jupyterhub, custom}.
        # type: simple

        type: jupyterhub

        jupyterhub:
          # A JupyterHub api token for dask-gateway to use. See
          # https://gateway.dask.org/install-kube.html#authenticating-with-jupyterhub.
          apiToken: "89fa0a50e9cf1dc3447c7b757301bd3a275aa334db947560802c2f428223ed5c"

          # The JupyterHub Helm chart will automatically generate a token for a
          # registered service. If you don't specify an apiToken explicitly as
          # required in dask-gateway version <=2022.6.1, the dask-gateway Helm chart
          # will try to look for a token from a k8s Secret created by the JupyterHub
          # Helm chart in the same namespace. A failure to find this k8s Secret and
          # key will cause a MountFailure for when the api-dask-gateway pod is
          # starting.

          # apiTokenFromSecretName: hub
          # apiTokenFromSecretKey: hub.services.dask-gateway.apiToken

          # JupyterHub's api url. Inferred from JupyterHub's service name if running
          # in the same namespace.
          # apiUrl: "https://10.254.39.16:8001/hub/api"