apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dask
  namespace: dask
  annotations:
    flux.weave.works/automated: "false" 
   
spec:
  releaseName: daskhub
  interval: 5m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: dask-charts
        namespace: dask
      interval: 1m
      chart: daskhub
      version: 2023.1.0

  # valuesFrom:
  #   - kind: Secret
  #     name: daskhub
  #     valuesKey: values.yaml

  values:
    jupyterhub:
      proxy:  
        service:
          type: LoadBalancer
          loadBalancerIP: 137.138.6.73 
        https:
          enabled: true # true
          hosts:
            - nb-vre.cern.ch
          type: secret
          secret:
            name: cern-sectigo-tls-certificate
        # secretToken: ###
      hub:

        services:
          dask-gateway: {}
            # apiToken: ###
        networkPolicy:
          enabled: false   
        db:
          type: sqlite-memory
          upgrade: true

        config:
          GenericOAuthenticator:
            client_id: 
              valueFrom:
                secretKeyRef:
                  name: jhub-cvre-iam-secrets
                  # namespace: jhub
                  key: client_id
            client_secret: 
              valueFrom:
                secretKeyRef:
                  name: jhub-cvre-iam-secrets
                  # namespace: jhub
                  key: client_secret
            oauth_callback_url: https://nb-vre.cern.ch/hub/oauth_callback
            authorize_url: https://iam-escape.cloud.cnaf.infn.it/authorize
            token_url: https://iam-escape.cloud.cnaf.infn.it/token 
            userdata_url: https://iam-escape.cloud.cnaf.infn.it/userinfo
            scope:
              - openid
              - profile
              - email
              - offline_access
            username_key: preferred_username
          JupyterHub:
              authenticator_class: generic-oauth
              # authenticator_class: dummy
      singleuser:
        storage:
          type: none
        # image:
        #   name: ghcr.io/vre-hub/dask-root  # Image to use for singleuser environment. Must include dask-gateway.
        #   tag: "latest"
        defaultUrl: "/lab" 

    dask-gateway:
      gateway:
        auth:
          jupyterhub:
            apiTokenFromSecretName: hub
            apiTokenFromSecretKey: hub.services.dask-gateway.apiToken
            # apiToken: ###
    dask-kubernetes:
    #   # Use dask-kubernetes, rather than Dask Gateway, for creating Dask Clusters.
    #   # Enabling this also requires
    #   # 1. Setting `jupyterhub.singleuser.serviceAccountName: daskkubernetes`.
    #   # 2. Ensuring that `dask-kubernetes` is in your singleuser environment.
      enabled: true

