apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daskhub-vre-dynamic
  namespace: daskhub
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: manila-meyrin-cephfs-retain
  