apiVersion: v1
kind: Pod
metadata:
  name: rucio-root-client
  namespace: rucio
spec:
  containers:
  - name: rucio-client
    image: rucio/rucio-clients:release-34.6.0
    imagePullPolicy: Always
    volumeMounts:
    - name: cern-bundle
      mountPath: /etc/pki/tls/certs/
    env:
    - name: RUCIO_CFG_CLIENT_RUCIO_HOST
      value: "https://vre-rucio.cern.ch"
    - name: RUCIO_CFG_CLIENT_AUTH_HOST
      value: "https://vre-rucio-auth.cern.ch"
    - name: RUCIO_CFG_CLIENT_CA_CERT
      value: "/etc/pki/tls/certs/CERN-bundle.pem"
    - name: RUCIO_CFG_CLIENT_ACCOUNT
      value: "root"
    - name: RUCIO_CFG_CLIENT_AUTH_TYPE
      value: "userpass"
    - name: RUCIO_CFG_CLIENT_USERNAME
      valueFrom:
        secretKeyRef:
          name: rucio-root-account
          key: root-username
    - name: RUCIO_CFG_CLIENT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rucio-root-account
          key: root-password 
    command: ["sleep","3600"]
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
  volumes:
    - name: cern-bundle
      secret:
        secretName: cern-bundle
        


