apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ui
  namespace: rucio

spec:
  releaseName: ui
  interval: 5m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: rucio-charts
        namespace: rucio
      interval: 1m
      chart: rucio-ui
      version: 34.0.5

  valuesFrom:
    - kind: Secret
      name: rucio-db
      valuesKey: dbfullstring
      targetPath: config.database.default
  
  values:
    additionalSecrets:
      - volumeName: idpsecrets
        secretName: idpsecrets
        mountPath: /opt/rucio/etc/idpsecrets.json
        subPath: idpsecrets.json

    replicaCount: 1
    exposeErrorLogs: True

    service:
      type: LoadBalancer
      port: 443
      targetPort: 443
      protocol: TCP
      name: https
      #useSSL: true

    image:
      repository: rucio/rucio-ui
      tag: release-34.6.0
      pullPolicy: Always

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

    minReadySeconds: 5

    proxy:
      rucioProxy: "vre-rucio.cern.ch"
      rucioProxyScheme: "https"
      rucioAuthProxy: "vre-rucio-auth.cern.ch"
      rucioAuthProxyScheme: "https"

    # ingress:
    #   enabled: true
    #   annotations:
    #     kubernetes.io/ingress.class: nginx
    #     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #     nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #   path: /
    #   hosts: 
    #     - vre-rucio-ui.cern.ch
        
    ## values used to configure apache
    httpd_config:
      legacy_dn: "False"
      rucio_hostname: "vre-rucio-ui.cern.ch"
      
    config:
      policy:
        permission: "escape" # "generic"
        schema: "escape" # "generic"
        # lfn2pfn_algorithm_default: "identity"

      oidc:
        idpsecrets: "/opt/rucio/etc/idpsecrets.json"
        admin_issuer: "escape"
        expected_audience: "rucio"
        expected_scope: "openid profile"

      # credentials:
      #   gcs: "/opt/rucio/etc/rse-accounts.cfg"

    resources:
      limits:
        cpu: 200m
        memory: 800Mi
      requests:
        cpu: 200m
        memory: 500Mi
