apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: daskhub-vre-dbconnectstring
  namespace: daskhub
spec:
  encryptedData:
    dbconnectstring: AgAoaCl7wXVK/sHLjWUys0l0B8S1ayTkNxE1MntGyndi26mCQ5xVrBo0me0th3FnyLlfHbvi6IiTNPP0kwahp3T8nHi2GFlu4NGD3WaMgEkFGptGM2le/16k755TKgZiAYiW0llk97XO2muWrSrW67aqlTgg5kSi9/djtvdls461aFp4cAVYe1iy0xja6O4myA6cD16Sd/4PCDcvJdKr/zCu8uvQD80eD7pxNH71zVa+I3VT/Nj0JhWDechuHi+MOxEAmFPHHjOL/rQ2B8I8twDhgpQdBOurnUlqRl/1MH5VEP0OWo719icHnaR0UgMJrctxhKti+d5KR6i5A8GCklf94VFV7jMHIWiVQhPaWbBlzvsJJ3YQNjgkdhImB4w/5jDL7uf3X/xflE31NkEVjavCWEarqXQjoS568F4No6PKYKWPDUlt3EwGvuJ7DA98+Zi5kymGEbvOWgyIlMO5tqBE1bguKM3g4gt3LibgWgCalJT+3J09IKK6l2cOPZ2Zm2MRGDgGpY3bWH+i718VO7Yb7aIJ2Z1N2MrjUbRc8+DE0ABirk6M02MkO9ElTe8Q3UvIpEDx9j5hVLEycjsgIcb5fzML5b0AiAUoAkDo243tYTiKGMdB7bFqSQgaCQnab1RY250PZarreys+LglV88hN1SBH3sDgfRMGoTzvdFcASdn0Cps0o8rJPou1giKrTEIGjkZIUKCSO/Lwl+wCFpKxf+CJcbmtL8ElatFjwNRsqmruJ4YEZWGtpaUugSoAzHXKjxMGCwUYpTwxjwU5aNlc1u5hvadE196Vqg==
  template:
    metadata:
      creationTimestamp: null
      name: daskhub-vre-dbconnectstring
      namespace: daskhub
    type: Opaque

