apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nb-vre-iam-client
  namespace: daskhub
spec:
  encryptedData:
    client_id: AgBx9OkYfIfEJJVxW9Z2Fj4L+QQLn03Wf2xIt4upr1WlH9IDPeR62Sma1SqUPHdlwXR8WrQ7hx67gL5bL207ZQANU6Ox4L4cgYkCQm4egZc35zwFEGuPu20Ybvf92NjrElIdkVzLwTMA1p8ffuk/1fs7Cl0yl8qclOgW4yfRGt9WKVcGoZqmXhWlJlGmh6Ujb6M6hMkLmJslamprRXXteUUB7j2d8sGMkIcZaJ4fEWqOZuDiTobc/dGSPuWQk0mwtJ8EJugjMO48pnhGEOcmxjz53JUtpCS6mtgE+SmD6lUsIkLo3Mln6Go/A+wxzbsJkUq7LfREjBBYcB6Su+Lqk0IGpvBShwPCyZYepRWXEdfpfNIZMAHZrRfw9tv0tNzF67XN9y4EJ6t4xWtzZEyiLrH6zLN0wkINvIymMTzcwjpPTsvmvLCg10/mWyH8JLVGo1rQVa/AfKSEKad7OtCPyWT1EEPJPxSjA7B7P1sMtxU9HLpfEKtjF3MyV50DXDKTxr6TJwn3EVlCAsDpgqqnbJepKmWptl0cn/AuPd7sSawhuqndRvoX1r6LwNT6DJ+yyLp42YBs8VJ+PItP6gTr3MAdt2UYtZhP7z5hD1M1KMtjSfg7Bn5riF02T9O7TUuF0ryZutALpYH0LAmylJahptIE5woexL7pUklkZxIPbTi7ljya1nUyr35rZRu1IIuHcAHzzCikBlDoihABjQbzSx6BtfiEddoxPTR/5jxQN4EMXwJudX0=
    client_secret: AgB8Lw8pmRB1WFhb2X3zfiG9dArm9hIQ8CRQjpLYCnb1cFWlKQIj53DHNCfmoUvuJW9Py89eUtpEvHdClA2E5LarQ0ctTOiT0Q8i0X6Qs6XxabGu3WkngpVNqOnn5Wx8DetuU+XQz8Ckaf9GFbioa2CusNJifLYpBYDcjd9LxYNKFWrSq6hdzsV84FbcYHgMF2AP5JAG9ml1KqkWDu00zrbISojhzWSQUjY5npCOwzRLY9muxxIeFTjO0YbuotcRwgt7njSlkSpCH6ax/KUTYCeY9j5PL7Oq85tCYfK+Q6lsWAm+sa5PX0BnUbK7dcXz7RaMdYy7I+wMdjcPegkY9CbHYjKkGLJmMVyY0J6E/4987ZsrJDhMOn6CpGoLdALwCTNR/9Fa/o/DxRLeQdAxIbOS5d1UI/knF6mlkrQXXdhDHa4INcBoHnZ3fedVersont2TZ5vhTpDvyLhNIL5C/++MJBaND2RA8jZsHSSpy6vRO4LNE5rm0FkZwSX7FaDGWNwWSVTsNWNU36jg24/8Pl5y/LyUgIZ9Xy4QHJCvtqHG/1lIHnFvWWQRrYfsPzyBdfipmfKNi505ogR7tW+WgMnE0XXajzZZCpbSP6IcbNkew/fXzTXDHRE3gv34ONxsymDFKB/nr3rX2BJ6CvEnLYAarI2NQlCQQRpI+YF8lKRqZol42qVImuBE3eFEOO9XkgU8f1lJFc4w4dWrVM/EJFiJ5Hfqb1OFFxS2lBxErC4vYR0ijCwgl2KOqA9rLLmG0A6oHSnRj2tPR3Y1OY9YfXbW7nRc4A/omVPEDYoE2T0WPodGvxR8bg==
  template:
    metadata:
      creationTimestamp: null
      name: nb-vre-iam-client
      namespace: daskhub
    type: Opaque

