name: Docker automatic build and publish when changes in container dir

on: 
  push:
    branches:
      - ci_changes_in_containers
#  pull_request:
#    branches:
#      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-matrix-from-changed-dirs:
    runs-on: ubuntu-latest 
    name: Build matrix from directories with changed files

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # "0" (OR "2" -> To retrieve the preceding commit).

      - name: Run changed-files with dir_names
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_ignore: |
            .github/**
            infrastructure/**
            .gitignore
            *.md
            *.png
            LICENSE
            **/README.md
          dir_names: "true"
          dir_names_exclude_current_dir: "true"

      - name: List all changed dirs 
        id: format-output
        run: |
          containers=()
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$dir was changed"
            tmp_dir=$(echo $dir | cut -d'/' -f2)
            containers+=("\"${tmp_dir}\"")
          done

          CONT_LIST=`echo "[${containers[@]}]" |  sed 's/ /,/g'`
          echo "Updated containers list: $CONT_LIST"

          echo ::set-output name=container_list::$CONT_LIST
      
    outputs:
      modified_containers: ${{ steps.format-output.outputs.container_list }}  

  build-and-push-modified-containers:
    needs: build-matrix-from-changed-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: ${{ fromJSON(needs.build-matrix-from-changed-dirs.outputs.modified_containers) }} 
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker Checkout
        uses: actions/checkout@v4

      - name: Get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check env output
        run: echo "tag" is ${{ env.RELEASE_VERSION }}

      - name: Action for git describe
        id: ghd
        uses: proudust/gh-describe@v1

      - name: Log in to the GH Container Registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for ${{ matrix.containers }}
        id: metadata
        uses: docker/metadata-action@v5.3.0
        with:
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.ghd.outputs.tag }}-${{ steps.ghd.outputs.distance }}-${{ steps.ghd.outputs.sha }}
          # ghcr.io/vre-hub/{vre}-{container_name}:{tag}
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ matrix.containers }}

#      - name: Build and push ${{ matrix.containers }}
#        id: build
#        uses: docker/build-push-action@v5.1.0
#        with:
#          context: containers/${{ matrix.containers }}
#          file: containers/${{ matrix.containers }}/Dockerfile
#          push: true
#          tags: ${{ steps.metadata.outputs.tags }}
#          labels: ${{ steps.metadata.outputs.labels }}
#          build-args: | 
#            BUILD_DATE=$(date +'%Y-%m-%dT%H:%M:%SZ')
#            TAG=${{ env.RELEASE_VERSION }}


#          echo ::set-output name=container_list::$CONTAINERS_LIST
#
#          echo "The final list is: ${CONTAINERS_LIST}"
#
#          myArray=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${myArray[@]}")
#          echo "Updated array list: $myArray"
#          echo "array=$myArray" >> $GITHUB_OUTPUT