name: "Merge Check for non-Terraform and Flux files"

on: 
  pull_request:
    paths-ignore:
      - '**.tf'
      - 'infrastructure/cluster/flux/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**.tf'
      - 'infrastructure/cluster/flux/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'  

