name: flux check pipeline # Merge Check Workflow for Terraform and Flux Files if not changed ref. to : https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

on: 
  pull_request:
    paths-ignore:
      - 'infrastructure/cluster/flux/**'

jobs:
  flux-validate:
    name: "Validate Flux files"
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No check required"'
